### PR TITLE
Trigger param

### PR DESCRIPTION
**Pull request by cosmicog**
I did the changes that requested by reviewers.

### CODE REVIEW

**Comment by cosmicog** [comment]
I needed to do this change to my fork for triggering my MAPIR Survey3. I tested with hitl and the camera is triggered by pixhawk. I'm just not sure about adding variables and naming them correctly.

**Comment by hamishwillee** [comment]
@cosmicog YOu've made this in the wrong repo - this is my private fork :-)

Resubmit in https://github.com/PX4/Firmware

**Comment by cosmicog** [comment]
Believe me, I was confused when I was opening here, it's for the first time in my life, editing someone else's pull request :-) 

But;

You have an [active pull-request](https://github.com/PX4/Firmware/pull/10913) into the `PX4:master` from this `hamishwillee:trigger_param` branch. 
I didn't imagine any other way to not destroy your contributions. _When you push commits here, to the `hamishwillee:trigger_param`, your pull request at the main repository is automatically being updated._

**Comment by cosmicog** [comment]
Since you did same changes after i did + renamed variables too, I see no point on creating multiple PRs.

**Comment by hamishwillee** [comment]
Thanks. YOu triggered me to do the extra work, so thank you.

**Comment by hamishwillee** [comment]
And yes, I could have merged your work, but I don't do all that much programming, so it was good practice for me.

**Pull request closed without merging**
